### ISSUE TITLE
Logo and search bar in header

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-sentinels#1]
# Story

As a user, in order to find attractions I'm interested in, I need to type some value in a text box in the navigation bar at the top of the page, press enter, and see results

# Acceptance Criteria

**Given** a user visits the application
**When** the application renders
**Then** the application logo should appear on the left in a navigation bar

**Given** a user visits the application
**When** the application renders
**Then** a text field should appear in the middle of the navigation bar

**Given** the user types some characters into the search field
**When** user user presses enter
**Then** the areas that contain an attraction, whose name contains the search string, should be outlined with a border

# Technical Information

1. Use regular expressions to match the user's search string with the name of each attraction to find a match. The search string simply must be contained in the attraction name, not just start with.

**Comment by DreRandaci** [comment]
index.html: 
-bootstrap navbar with centered search bar and search button
-Logo on leftmost side of nav
-Time selection boostrap drop down
-prompt user to authenticate using hardcoded modal
-fire off firebaseApi.js promises, enter data.js to combine data and enter domHandler to print page

**Comment by DreRandaci** [comment]
events.js:
-searchBarEnter (fires filter func on keypress 'Enter', fires filter func, passes searchBar val)
-searchBarClick (fires filter func on btn click, passes searchBar val)
-filterSearchTxt filters txt using clicky-planets filtering example

`let searchBar = grab search bar element`
`const searchBarEnter = ( event ) => {`
`if 'enter' is pressed, grab search txt, fire filterSearchTxt( txt )`

`const searchBarClick = ( event ) => {`
`on search button click, grab search txt, fire filterSearchTxt( txt )`
