### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-sentinels#14]
# Story
As a developer, when I look at your readme,  I would like it to be real nice looking and very useful.

# Acceptance Criteria

**When** anyone looks at your readme
**Then** they should know everything they need to know about your project.

**Comment by RobertShock** [comment]
<img width="1680" alt="screen shot 2017-11-08 at 6 29 28 pm" src="https://user-images.githubusercontent.com/30094328/32582203-37e8b4d8-c4b3-11e7-9998-c5a8c632b3e9.png">
