### ISSUE TITLE
Areas should be displayed in rectangular grid

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-sentinels#2]
# Story

As a user, in order to see where areas are located, I need to see the park laid out in a grid

# Acceptance Criteria

**Given** the area data has been loaded
**When** the application renders
**Then** the areas should be represented to the user as a 3-3-2 grid, with the middle cell of the last row unoccupied, and each area colored with its corresponding hex value (i.e. the `colorGrid` value)

<table>
  <tr>
    <td>1</td>
    <td>2</td>
    <td>3</td>
  </tr>
  <tr>
    <td>4</td>
    <td>5</td>
    <td>6</td>
  </tr>
  <tr>
    <td>7</td>
    <td></td>
    <td>8</td>
  </tr>
</table>

**Comment by DreRandaci** [comment]
`const domHandler = ( parkArray ) => {
    `//prints bootstrap grid attaching an id to each `div`
    `let str = ''`
    `parkArray.forEach(( area ) => {` 
    `str += <div id=${area.areaName} class=${area.areaId}>`
}`
