### ISSUE TITLE
"Out of Order" rides should be fixed upon first maintenance ticket being completed

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-sentinels#29]
# Story

As a park administrator, I should be able to have my ride status fixed upon maintenance being completed.

# Acceptance Criteria

**Given** a ride is "out of order"
**When** the first maintenance ticket is completed
**Then** my database should be updated to reflect that the ride is no longer out of order
**And** any remaining maintenance tickets should stay scheduled, but should be considered "upkeep"

**Comment by DreRandaci** [comment]
grab current time, check vs. the scheduled maintenance time, when the maintenance date is present or passed, check the maintenance duration, change the parkAttractions.out_of_order to false, else change it to 'Upkeep', send updated file to firebase ("PUT"). should be listening for time change continuously 

questions:
-should the actual JSON file be changed or just the firebase data
-does it need to re-render in real time on the page as maintenance dates pass

**Comment by DreRandaci** [comment]
if attraction has out_of_order key/value
-if todays month/day/year === the maintenance date
--if  currentTime > maintenanceDuration + maintenanceStartTime
---out_of_order: false;
--else if maintenanceStartTime > currentHour 
---out_of_order: "upkeep"
----then, out_of_order: false (if currentHour > maintenanceDuration + maintenanceStartTime?)

-convert maintenance date to integer
-check against current date as integer
-update by matching the attraction.id
