### ISSUE TITLE
User should be able to see all attractions in an area

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-sentinels#3]
# Story

As a user, in order to explore attractions near me, I need to highlight an area of the park and see all attractions in it

# Acceptance Criteria

**Given** user wants to see the attraction list of an area
**When** the user clicks on an area
**Then** all attraction names assigned to that area should be listed in the left 30% of the screen
**And** the attraction type should be in parenthesis next to the name
**And** the name should be a hyperlink

**Comment by DreRandaci** [comment]
events.js:
-on area click, sort data array by matching `areaName` with clicked `div id`
-grab data: parkArray = data.getParkArray()

`const showSelectedAttractions = ( parkArray ) => {`
    `let parkContainer = $(#parkContainer)`
    `parkContainer.click(( e ) =>`
    `parkArray.forEach(( area ) =>`
        `if ( e.target.id === area.areaName)`
        `grab attractions and attraction types, fire buildLeftDomString( attractions, types )`

**Comment by DreRandaci** [comment]
`let searchBar = grab search bar element`
`const searchBarEnter = ( event ) => {`
`if 'enter' is pressed, grab search txt, fire filterSearchTxt( txt )`

`const searchBarClick = ( event ) => {`
`on search button click, grab search txt, fire filterSearchTxt( txt )`

**Comment by DreRandaci** [comment]
domHandler.js:
-make buildLeftDomString func
-make printLeftDom func to print to the left 30% of page

`const buildLeftDomString = ( attractions, types ) => {`
`use bootstrap drop down to print to the left div with attraction names`
`fire printLeftDom( string )`
