### ISSUE TITLE
User should be able to see attraction details

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-sentinels#4]
# Story

As a user, in order to see attraction details or event times, I need to be able to select an attraction and see all available information about it

# Acceptance Criteria

**Given** the user has clicked on an area
**When** the user clicks on a specific attraction's hyperlink
**Then** the description of the attraction, and/or its hours of operation must be displayed directly beneath the hyperlink, and before the next one
**And** any previously displayed attraction details must disappear

**Comment by DreRandaci** [comment]
events.js:
-click event for attraction name hyperlinks in left div
-bootstrap dropdown menu displays attraction description, hours of operation
-hide any previously displayed attractions

**Comment by DreRandaci** [comment]
events.js:

`const showAttractionDetails = () => {`
`let leftOutputDiv = get element`
`leftOutputDiv.on( 'click', '.class' => {`
`show attraction info, hide other attractions`
