### ISSUE TITLE
User must see copyright information

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-sentinels#5]
# Story

As a user, in order to know when the content was last updated, I need to see the date of the copyright

# Acceptance Criteria

**Given** user visits the application
**When** the page is rendered
**Then** there should be a copyright notice in a footer element with the current year and today's date.

**Comment by DreRandaci** [comment]
index.html:
-add footer with contributors and copyright/date created

**Comment by RobertShock** [comment]
Created footer which contains all contributors, copyright 2017 and added dynamic date stamp.
